"""Atualizacao da estrutura social do perfil

Revision ID: f7cf704d01ff
Revises: 
Create Date: 2026-09-03 11:00:36.496633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7cf704d01ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('funcao', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.Column('github', sa.String(length=150), nullable=True),
    sa.Column('instagram', sa.String(length=150), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('capa', sa.String(length=255), nullable=True),
    sa.Column('data_entrada', sa.String(length=30), nullable=True),
    sa.Column('projetos_ativos', sa.Integer(), nullable=True),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('advertencias', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('cor', sa.String(length=20), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('data_entrega', sa.String(length=30), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['responsavel_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('midia_url', sa.String(length=255), nullable=True),
    sa.Column('tipo_midia', sa.String(length=20), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=True),
    sa.Column('codigo_snippet', sa.Text(), nullable=True),
    sa.Column('codigo_linguagem', sa.String(length=30), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='_post_user_uc')
    )
    op.drop_table('user')
    op.drop_table('post')
    op.drop_table('card')
    op.drop_table('post_curtida')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_curtida',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=150), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cor', sa.VARCHAR(length=30), nullable=True),
    sa.Column('data_criacao', sa.DATETIME(), nullable=True),
    sa.Column('pontuado', sa.BOOLEAN(), nullable=True),
    sa.Column('responsavel_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['responsavel_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('texto', sa.TEXT(), nullable=True),
    sa.Column('data_criacao', sa.DATETIME(), nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('midia_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tipo_midia', sa.VARCHAR(length=20), nullable=True),
    sa.Column('arquivo_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('arquivo_nome', sa.VARCHAR(length=255), nullable=True),
    sa.Column('codigo_snippet', sa.TEXT(), nullable=True),
    sa.Column('codigo_linguagem', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('senha_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('funcao', sa.VARCHAR(length=100), nullable=True),
    sa.Column('foto', sa.VARCHAR(length=255), nullable=True),
    sa.Column('capa', sa.VARCHAR(length=255), nullable=True),
    sa.Column('projetos_ativos', sa.INTEGER(), nullable=True),
    sa.Column('data_entrada', sa.VARCHAR(length=50), nullable=True),
    sa.Column('localizacao', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('cargo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('advertencias', sa.INTEGER(), nullable=True),
    sa.Column('pontos', sa.INTEGER(), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('github', sa.VARCHAR(length=255), nullable=True),
    sa.Column('instagram', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('post_likes')
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('cards')
    op.drop_table('users')
    # ### end Alembic commands ###
